### PR TITLE
Test occupation lookup

### PR DESCRIPTION
**Pull request by jonnyshaw89**

### CODE REVIEW

**Comment by armstrongb** [comment]
### Odd returns
**Search term:** `primary`

**Results returned:**
- Primary helper
- Primary teacher
- Supply teacher (primary headteacher primary education)
- Secretary (primary education)
- Caretaker (primary education)
- Administrator (primary school)
- Cleaner (primary school)
- Instructor (primary school)
- **Primary care facilitator** - _why would these be the last two of these 10 results? Primary is 1st full word on each_
- **Primary school teacher**

**Search term:** `nurse`
- Nurse
- Nursery nurse
- Ancillary nurse
- Auxiliary nurse
- Charge nurse
- Nurse-tutor
- Paediatric nurse
- Companion-nurse
- **Nurse adviser** - _why would these be the last two of these 10 results? Primary is 1st full word on each_
- **Nurse supervisor**

### 10 results

Returning only 10 results is meaning that a number of options are being omitted. 
**For example:** `nurse` misses
- `intensive care nurse`
- `registered nurse`
- `registered children's nurse`
- `state registered nurse`
- `registered sick children's nurse`

And possibly others.

**Comment by armstrongb** [comment]
**Search term:** `farm`

- Farm worker (fish farm, hatchery) - _if this is 1st as it has `farm` twice..._
- Farm labourer
- Farm worker (dairy farm) _... how is this third?
- Farm contractor
- Farm help
- Farm mechanic
- Farm owner
- Farm worker
- Farm agent - _how isn't this 3rd?_
- Farm foreman

**Missing results**
Many `farm` related terms missing as restricted to 10.

**Comment by armstrongb** [comment]
**Search term:** `electrical engin` (to try `electrical engineer`)

- Chief inspector (engineering, professional, electrical engineering)
- Electrical engineer _**- not 1st**_
- Chief electrical engineer
- Electrical service engineer
- Checker (electrical, electronic engineering)
- Insulating winder (electrical engineering)
- Leading hand (electrical engineering)
- Research assistant (engineering, electrical)
- Service supervisor (electrical engineering)
- Tape winder (electrical engineering)

**Search term:** `electrical engineer`
Where has `electrical engineer` gone from the results?

- Auto electrical engineer
- Colliery electrical engineer
- Electrical engineer's fitter
- Engineer (professional, electrical)
- Maintenance electrical engineer
- Senior electrical engineer
- Electrical and Mechanical engineer
- Mechanical and Electrical engineer
- Operations director (mechanical electrical engineering)
- Research associate (engineering, electrical)

**Comment by dwyeradam** [comment]
@armstrongb we're working on refining multi word searches at the moment. This works a lot better with single words but adding additional priority on each word isn't quite working as planned.

**Comment by armstrongb** [comment]
@dwyeradam I'll leave it there for now but those search terms above seem to give a reasonable set of re-test scenarios.

**Pull request closed without merging**
